### ISSUE TITLE
Choose between Markdown and reStructured Text

### ISSUE THREAD

**Issue by norbertvandijk** [gofair-foundation/fip#27]
We may have to reconsider the change from MKDocs to Sphinx. MkDocs is relatively straightforward and works best with Markdown. Sphinx is less straightforward but has richer features, is more advanced and works best with reStructured Text although with the use of the proper package it can also process Markdown which it does in our wiki now. 

MkDocs may be more suited for maintenance of basic documentation written in markdown than Sphinx with Sphinx possibly being overly complicated for our purposes.

- https://jamstack.org/generators/mkdocs/
- https://jamstack.org/generators/sphinx/

I will look into it.

**Comment by mabablue** [comment]
well, I have no experience with neither those so... ask either Anne or Robin
