### ISSUE TITLE
Add "Contributing" page to wiki

### ISSUE THREAD

**Issue by norbertvandijk** [gofair-foundation/fip#51]

**Comment by norbertvandijk** [comment]
Add "Contributing" page to wiki

**Comment by norbertvandijk** [comment]
How to contribute to the FIP wiki via Github

Go to https://github.com/gofair-foundation/fip
Creat a user profile if you don’t have one
Create a fork of the [gofair-foundation](https://github.com/gofair-foundation)/[fip](https://github.com/gofair-foundation/fip) in your own repository
In the docs folder you will find the markdown files (filename.md), which are the files that are used to make the static pages on the wiki website, and the _static/img folder, which contain all the images that are shown in the wiki pages.
If you wish to contribute to the text, first of all be sure that your fork is syncronised with the original GFF repository. To do so, open your fork, and click on “Sync fork”, then synchronise your fork by clicking on “update branch”.
When the fork is synchronised, you can start editing the markdown files from your repository. 
Open the markdown file which correspond to the chapter you want to contribute to.
Click on “edit this file” button on the top right of the page.
The “edit” page will appear. 
After having introduced your changes, click on “commit changes”.
Click on “pull request” button on the top left of the page, then “new pull request”
At this point a new request has been pulled. The mantainers will revise your request and accept it if needed.

**Comment by norbertvandijk** [comment]
@datara44 I suggest we write generic instructions as much as possible and avoid editor specific details of how to edit a markdown file since this can be done in a number of different code editors.

**Comment by datara44** [comment]
I would put the link of the GFF fip github repo in the wiki page
